print("hiiiiiiiiiii ")
print("Mounika")
print("hiiiiiiiiiii ")
print("hiiiiiiiiiii ")
print("Varshi")
print("helloooo")
print("helloooo")
print("goodmrng")
print("meghana")
print("hiiiiiiiiiii ")
print("hiiiiiiiiiii ")
print("hiiiiiiiiiii ")
print("helloooo")
print("helloooo")
print("helloooo")
print("goodmrng")
print("goodmrng")
print("goodmrng")